version: '3'

services:
  mariadb:
    build:
      context: .
    image: mariadb:v1
    container_name: mariadb_container
    restart: always
    env_file:
      - ../../.env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  mariadb_data: