version: '3'

services:
  mariadb:
    build:
      context: srcs/requirements/mariadb
    image: mariadb:v1
    container_name: mariadb_container
    networks:
      - wp-nginx-mariadb
    restart: always
    env_file:
      - srcs/.env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10

  nginx:
    build:
      context: ./srcs/requirements/nginx
    container_name: nginx_container
    networks:
      - wp-nginx-mariadb
    image: nginx:v1
    restart: always
    ports:
      - "443:443"
    env_file:
      - srcs/.env
    volumes:
      - wordpress_data:/var/www/html/wordpress
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
    container_name: wordpress_container
    networks:
        - wp-nginx-mariadb
    image: wordpress:v1
    restart: always
    env_file:
      - srcs/.env
    volumes:
      - wordpress_data:/var/www/html/wordpress
    depends_on:
      mariadb:
       condition: service_healthy

  sshdocker:
    build:
      context: ./srcs/bonus/ssh
    container_name: ssh_container
    image: ssh:v1
    restart: always
    ports:
      - "7854:7854"
    networks:
      - sshnet
    volumes:
      - wordpress_data:/home/user/wordpress_vol
      - mariadb_data:/home/user/mariadb_vol

  adminer:
    build:
      context: ./srcs/bonus/adminer
    container_name: adminer_container
    image: adminer:v1
    restart: always
    ports:
      - "7853:80"
    networks:
      - wp-nginx-mariadb

  ftp:
    build:
      context: ./srcs/bonus/ftp
    container_name: ftp_container
    image: ftp:v1
    restart: always
    ports:
      - "7852:21"
      - "7851:20"
    networks:
      - ftserv

volumes:
  mariadb_data:
  wordpress_data:

networks:
  wp-nginx-mariadb:
  sshnet:
  ftserv: