FROM debian:buster

WORKDIR /app

RUN apt update \
	&& apt upgrade -y \
	&& apt install -y wget \
	&& apt install -y php7.3 php7.3-fpm php-mysql default-mysql-client

# a command-line interface for WordPress, you can manage WordPress once it's downloaded
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp

WORKDIR /var/www/html/wordpress

RUN wp --allow-root core download --version=6.2.2

RUN chown -R www-data:www-data /var/www/html/wordpress
RUN chmod -R 755 /var/www/html/wordpress

EXPOSE 9000

COPY ./tools/wpscript.sh /app/

RUN chmod +x /app/wpscript.sh

COPY conf/www.conf /etc/php/7.3/fpm/conf.d/www.conf

ENTRYPOINT ["/app/wpscript.sh"]