FROM debian:buster

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y wget
RUN apt-get install -y php7.3 php-fpm php-mysql

# a command-line interface for WordPress, you can manage WordPress once it's downloaded
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp

RUN apt-get update && apt-get install -y default-mysql-client
RUN apt-get install -y mariadb-client
RUN wget https://wordpress.org/wordpress-6.1.1.tar.gz -P /var/www/html
RUN cd /var/www/html \
	&& tar -xzf /var/www/html/wordpress-6.1.1.tar.gz \
	&& rm /var/www/html/wordpress-6.1.1.tar.gz

# ensure that the web server(nginx) has the necessary permissions to read and execute the files within the web root directory
RUN chown -R www-data:www-data /var/www/*
RUN chmod -R 755 /var/www/*

EXPOSE 9000

COPY ./tools/wpscript.sh ./
RUN chmod +x ./wpscript.sh

COPY ./conf/www.conf /etc/php/7.3/fpm/pool.d/www.conf

ENTRYPOINT ["bash", "./wpscript.sh"]

# WORKDIR /app

# RUN apt update \
# 	&& apt upgrade -y \
# 	&& apt install -y wget \
# 	&& apt install -y php7.3 php7.3-fpm php-mysql default-mysql-client

# # a command-line interface for WordPress, you can manage WordPress once it's downloaded
# RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
# 	&& chmod +x wp-cli.phar \
# 	&& mv wp-cli.phar /usr/local/bin/wp

# WORKDIR /var/www/html/wordpress

# RUN wp --allow-root core download --version=6.2.2

# RUN chown -R www-data:www-data /var/www/html/wordpress
# RUN chmod -R 755 /var/www/html/wordpress

# EXPOSE 9000

# COPY ./tools/wpscript.sh /app/

# RUN chmod +x /app/wpscript.sh

# COPY conf/www.conf /etc/php/7.3/fpm/conf.d/www.conf

# ENTRYPOINT ["/app/wpscript.sh"]