FROM debian:12

RUN apt update && apt upgrade && \
	apt install nginx -y && \
	apt install openssl -y 

COPY conf/nginx.conf /etc/nginx/nginx.conf

RUN openssl req -x509 -nodes -out /etc/ssl/certs/rferradi.42.crt -keyout /etc/ssl/private/rferradi.42.key -subj "/C=FR/ST=IDF/L=Paris/O=rayan/OU=42/CN=rferradi.42.fr"
RUN chmod 755 /var/www/html
RUN chown -R www-data:www-data /var/www/html

CMD ["nginx", "-g", "daemon off;"]