FROM debian:12

RUN apt update && apt upgrade 
apt install nginx -y 
apt install openssl -y 
mkdir confssl

COPY conf/nginx.conf /etc/nginx/nginx.conf \
conf/ssl /confssl

RUN openssl req -new -newkey rsa:2048 -days 365 -x509 -nodes -config conf -keyout /etc/ssl/private/rferradi.42.key -out /etc/ssl/certs/rferradi.42.crt
